kind: ConfigMap
apiVersion: v1
metadata:
  name: collections
data:
  collections.json: |-
    [
      {"name":"none","display_name":"None"},
      {"name":"collection_nomicai_embeddings","display_name":"Red Hat Openshift AI 2.9"}
    ]